#%RAML 1.0 DataType
type: object

properties:
  id?: integer
  number: string
  createdForUser: string
  createdDate: datetime
  desription: string
  attachmen: file
  priority: string
  additionalComments: string
  updatedBy: string
  updated: string
  resolved: datetime
  resolvedBy: string
  resolutionCode: integer
  resolutionNotes: string