sf:
  username: 'nevena.dovicin@devoteam.com.mulesjp'
  password: 'NevenaNevena1994'
  token: '99Quw0KttvxZEpz4rFa1PJlq7'
sn:
  username: 'admin'
  password: 'InstanceFr0-'
  address: 'https://devoteamfr.service-now.com/'
mq:
  url: 'https://mq-eu-west-2.anypoint.mulesoft.com/api/v1/organizations/7c8900b5-2dc2-4579-b26e-004126995e7d/environments/33239c06-5bef-44fa-a65b-13e2cd93d948'
  clientAppId: 'ecb7cab4d7dc4372a4553b7c2ad07a48'
  clientSecret: '053c663A1E024669b4c97340387f135d'
api:
  id: "18791659"