#%RAML 1.0 NamedExample

value:
  id: 1
  number: "INC1"
  createdForUser: "User1"
  createdDate: 2023-06-06T15:04:40.090Z
  desription: "This is update for User1"
  attachmen: "?"
  priority: "High"
  additionalComments: "This is additional comment for updating User1"
  updatedBy: "Admin"
  updated: "?"
  resolved: 2023-06-06T15:04:40.090Z
  resolvedBy: "Admin"
  resolutionCode: 123
  resolutionNotes: "Note for resolution"
