#%RAML 1.0 NamedExample

value:
  insert:
    id: 1
    nubmer: "INC1"
    createdForUser: "User1"
    createdDate: 2023-06-06T14:04:40.090Z
    description: "Incident created for user User1"
    attachment: "?"
    priority: "Medium"
    state: "?"
    shortDescription: "User1s incident"
    type: "?"
    additionalComments: "This is additional comment"
    channel: "?"
